// Generated by Wrangler by running `wrangler types --config proxy/wrangler.jsonc`

// eslint-disable-next-line @typescript-eslint/no-empty-interface,@typescript-eslint/no-empty-object-type
interface Env {
}
